FROM        --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL       author="Lucas Mcginnis" maintainer="lucas.mcginnis@lrmtheboss.com"

LABEL       org.opencontainers.image.source="https://github.com/lrmtheboss/BossDockerImages"
LABEL       org.opencontainers.image.licenses=MIT

RUN         apk add --update --no-cache ca-certificates curl unzip tar git jq wget
