name: build mariadb
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - mariadb/**

jobs:
  call:
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    uses: ./.github/workflows/BuildDeploy.yml
    with:
      tags: "[10.11, 11.4]"
      image_name: "mariadb"
      folder: "mariadb"
    secrets: inherit
