name: build redis
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - redis/**
jobs:
  call:
    uses: ./.github/workflows/BuildDeploy.yml
    with:
      tags: "[7]"
      image_name: "redis"
      folder: "redis"